Fix the file path of tar.c
calccrypto/tar pull request #18
Opened 2024-10-27 14:20 UTC by 1956425473q

Fixed the issue of moving filename, causing strncpy to copy not the full path, Also added cmake to make it easier to compile.

2024-10-30 23:09 UTC, calccrypto commented
Can you please show an example of what the change fixes?

2024-10-30 23:11 UTC, calccrypto commented
Please give both libraries proper names within CMakeLists.txt and rename the actual output files with `set_target_properties`.

2024-10-30 23:12 UTC, calccrypto requested changes
Change tabs to 4 spaces

2024-10-30 23:12 UTC, calccrypto commented on CMakeLists.txt
> +	"${PROJECT_SOURCE_DIR}/main.c"
Indent line continuations

2024-10-30 23:13 UTC, calccrypto commented on CMakeLists.txt
> +	"${PROJECT_SOURCE_DIR}/*"
Indent line continuations

2024-10-30 23:13 UTC, calccrypto commented on CMakeLists.txt
> +set(compile_shared_libraries 1)
Should these be `option`s?

2024-11-01 05:50 UTC, 1956425473q commented
> 您能否举例说明此更改修复了什么？

strncpy(entry -> name, filename + move, 100);
Here because the filename parameter is moved forward by 1, strncpy is not copying the full data of filename, for example, I want to copy the "/my_dir/my_file" file, because the filename is moved forward, causing strncpy to copy "my_dir/my_file", which is incomplete, if the name of the file does not contain the path, strncmp also only copies "y_file", instead of " my_file".

2024-11-01 05:54 UTC, 1956425473q commented
> 您能否举例说明此更改修复了什么？

Sorry, I made a mistake.

2024-11-01 05:55 UTC, closed without merging